apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - corporate-external-networks-guardrail.yaml
  - deny-all-allow-dns-monitoring-owned-namespaces.yaml
  - kubeapi-egress-guardrail.yaml
